namespace Rex.Core;

/// <summary>
/// Every value in config.json and where a person changes it: the Settings tab control that edits it,
/// a reason it is set somewhere else, or (until each gets one) no control yet. Search, the tests and
/// the site's settings page read it.
/// </summary>
public static class SettingsCatalogue
{
    public static readonly IReadOnlyDictionary<string, string> Controls = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Mirror.MaxSize"] = "MaxSize",
        ["Mirror.MaxFps"] = "MaxFps",
        ["Mirror.VideoBitRate"] = "BitRate",
        ["Mirror.VideoCodec"] = "VideoCodec",
        ["Mirror.Audio"] = "Audio",
        ["Mirror.AudioDup"] = "AudioDup",
        ["Mirror.AudioSource"] = "AudioSource",
        ["Mirror.AudioBitRate"] = "AudioBitRate",
        ["Mirror.VideoBufferMs"] = "VideoBuffer",
        ["Mirror.DownsizeOnError"] = "DownsizeOnError",
        ["Mirror.RenderDriver"] = "RenderDriver",
        ["Mirror.RecordFormat"] = "RecordFormat",
        ["Mirror.RecordOnStart"] = "Record",
        ["Mirror.ExtraArgs"] = "ExtraArgs",
        ["Mirror.CompatibilityKeyboard"] = "CompatibilityKeyboard",

        ["Sound.Volume"] = "SoundLevel",
        ["Sound.Muted"] = "SoundMuted",
        ["Sound.Step"] = "SoundStep",
        ["Sound.RememberPerPhone"] = "SoundPerPhone",
        ["Sound.StartMuted"] = "SoundStartMuted",
        ["Sound.MuteWhenHidden"] = "SoundMuteHidden",
        ["Sound.MuteWhenBehind"] = "SoundMuteBehind",
        ["Sound.MuteWhenLocked"] = "SoundMuteLocked",
        ["Sound.LowerWhileTyping"] = "SoundLowerTyping",
        ["Sound.LowerTo"] = "SoundLowerTo",
        ["Sound.LowerForMs"] = "SoundLowerFor",
        ["Sound.FadeMs"] = "SoundFade",
        ["Sound.Balance"] = "SoundBalance",
        ["Sound.FollowMixer"] = "SoundFollowMixer",
        ["Sound.ShowLevel"] = "SoundShowLevel",
        ["Sound.WheelOnButton"] = "SoundWheel",

        ["Session.TurnScreenOff"] = "TurnScreenOff",
        ["Session.StayAwake"] = "StayAwake",
        ["Session.PowerOffOnClose"] = "PowerOffOnClose",
        ["Session.RestartOnUnexpectedExit"] = "RestartOnCrash",
        ["Session.ScreenOffTimeoutSeconds"] = "ScreenOffTimeout",
        ["Session.KeepPcAwake"] = "KeepPcAwake",
        ["Session.StartApp"] = "StartApp",

        ["Wireless.Enabled"] = "Wireless",
        ["Wireless.EnableTcpipWhenUsbAvailable"] = "WirelessTcpip",
        ["Touchpad.TwoFingerToAndroid"] = "TwoFinger",
        ["Touchpad.Sensitivity"] = "Sensitivity",

        ["Input.RightClick"] = "RightClick",
        ["Input.MiddleClick"] = "MiddleClick",
        ["Input.BackButton"] = "BackButton",
        ["Input.ForwardButton"] = "ForwardButton",
        ["Input.ShiftClicks"] = "ShiftClicks",
        ["Input.KeyRepeat"] = "KeyRepeat",
        ["Input.MouseHover"] = "MouseHover",
        ["Input.ClipboardAutosync"] = "ClipboardAutosync",
        ["Input.LegacyPaste"] = "LegacyPaste",
        ["Input.Gamepad"] = "Gamepad",
        ["Input.SwipeLength"] = "SwipeLength",
        ["Input.SwipeMilliseconds"] = "SwipeMilliseconds",

        ["Zoom.Enabled"] = "HostZoom",
        ["Zoom.MaxZoom"] = "MaximumZoom",
        ["Zoom.WheelStep"] = "WheelSpeed",
        ["Zoom.ResetOnRotate"] = "ResetOnRotate",
        ["Zoom.InvertWheel"] = "InvertWheel",
        ["Zoom.ZoomAtPointer"] = "ZoomAnchor",
        ["Zoom.ShowNavigator"] = "Navigator",
        ["Zoom.NavigatorCorner"] = "NavigatorCorner",
        ["Zoom.NavigatorWidth"] = "NavigatorWidth",
        ["Zoom.NavigatorPicture"] = "NavigatorPicture",
        ["Zoom.NavigatorOpacity"] = "NavigatorOpacity",
        ["Zoom.NavigatorFrameRate"] = "NavigatorFrameRate",
        ["Zoom.NavigatorAlways"] = "NavigatorAlways",

        ["Copies.Most"] = "CopiesMost",
        ["Copies.Gap"] = "CopiesGap",
        ["Copies.MaxSize"] = "CopiesMaxSize",
        ["Copies.Remember"] = "CopiesRemember",

        ["Ambient.Enabled"] = "AmbientEnabled",
        ["Ambient.Opacity"] = "AmbientOpacity",
        ["Ambient.Blur"] = "AmbientBlur",
        ["Ambient.Placement"] = "AmbientPlacement",
        ["Ambient.Scaling"] = "AmbientScaling",
        ["Ambient.Size"] = "AmbientSize",
        ["Ambient.OffsetX"] = "AmbientOffsetX",
        ["Ambient.OffsetY"] = "AmbientOffsetY",
        ["Ambient.FlipHorizontal"] = "AmbientFlip",
        ["Ambient.EdgeFade"] = "AmbientEdgeFade",
        ["Ambient.TintStrength"] = "AmbientTintStrength",
        ["Ambient.TintHue"] = "AmbientTintHue",
        ["Ambient.FrameRate"] = "AmbientFrameRate",

        ["Hud.Enabled"] = "HudEnabled",
        ["Hud.Position"] = "HudPosition",
        ["Hud.Buttons"] = "HudButtons",
        ["Hud.HideSeconds"] = "HudDelay",
        ["Hud.Scale"] = "HudScale",
        ["Hud.Opacity"] = "HudOpacity",
        ["Hud.ShowMessages"] = "HudMessages",

        ["PatternGuide.Enabled"] = "PatternEnabled",
        ["PatternGuide.AutoShowOnKeyguard"] = "PatternAuto",
        ["PatternGuide.AutoDiscoverGeometry"] = "PatternDiscover",

        ["App.RunInBackground"] = "RunInBackground",
        ["App.OpenOnConnect"] = "OpenOnConnect",
        ["App.ConfirmSensitiveWrites"] = "ConfirmWrites",
        ["App.ScreenshotDirectory"] = "ScreenshotLocation",
        ["App.AutoRepairUsb"] = "AutoRepairUsb",
        ["App.AlwaysOnTop"] = "AlwaysOnTop",
        ["App.SidebarSide"] = "SidebarSide",
        ["App.TopBarButtons"] = "QuickButtonChoices",
        ["App.ShowHints"] = "ShowHints",
        ["App.NotifyConnections"] = "NotifyConnections",
        ["App.ShowFrameRate"] = "ShowFrameRate",
        ["App.ScreenshotFormat"] = "ScreenshotFormat",
        ["App.CopyScreenshots"] = "CopyScreenshots",
        ["App.ShowWhatsNew"] = "ShowWhatsNew",

        ["GlobalKeys.Enabled"] = "GlobalKeysEnabled",
        ["GlobalKeys.ShowHide"] = "GlobalShowHide",
        ["GlobalKeys.WhenBehind"] = "GlobalWhenBehind",
        ["GlobalKeys.WhenInFront"] = "GlobalWhenInFront",
        ["GlobalKeys.HideTo"] = "GlobalHideTo",
        ["GlobalKeys.ShowFullscreen"] = "GlobalShowFullscreen",
        ["GlobalKeys.TypeIntoPhone"] = "GlobalTypeIntoPhone",
        ["GlobalKeys.Announce"] = "GlobalAnnounce",
        ["GlobalKeys.Actions"] = "GlobalActions",

        ["Apps.ShowSystem"] = "AppsShowSystem",
        ["Apps.ShowPackages"] = "AppsShowPackages",
        ["Apps.SortBy"] = "AppsSortBy",
        ["Apps.Layout"] = "AppsLayout",
        ["Apps.ShowRecent"] = "AppsShowRecent",
        ["Apps.RecentCount"] = "AppsRecentCount",
        ["Apps.FavouritesOnControls"] = "AppsOnControls",
        ["Apps.FavouritesOnControlsMost"] = "AppsOnControlsMost",
        ["Apps.FavouritesInHud"] = "AppsInHud",
        ["Apps.FavouriteKeys"] = "AppsKeys",
        ["Apps.ReadOnConnect"] = "AppsReadOnConnect",
        ["Apps.OpenFresh"] = "AppsOpenFresh",
        ["Apps.CloseWhenMirrorStops"] = "AppsCloseOnStop",
        ["Apps.Hidden"] = "AppsShowHidden",

        ["Transfer.Enabled"] = "TransferEnabled",
        ["Transfer.Folder"] = "TransferFolder",
        ["Transfer.SortMedia"] = "TransferSortMedia",
        ["Transfer.Folders"] = "TransferFolders",
        ["Transfer.InstallApks"] = "TransferInstallApks",
        ["Transfer.Replace"] = "TransferReplace",
        ["Transfer.AllowDowngrade"] = "TransferAllowDowngrade",
        ["Transfer.GrantPermissions"] = "TransferGrantPermissions",
        ["Transfer.AllowTestApps"] = "TransferAllowTestApps",
        ["Transfer.ConfirmInstall"] = "TransferConfirmInstall",
        ["Transfer.ConfirmDrops"] = "TransferConfirmDrops",
        ["Transfer.ConfirmOverMb"] = "TransferConfirmOver",
        ["Transfer.WhenNameExists"] = "TransferWhenExists",
        ["Transfer.ScanMedia"] = "TransferScanMedia",
        ["Transfer.OpenAfterInstall"] = "TransferOpenAfterInstall",
        ["Transfer.ShowFolderAfter"] = "TransferShowFolderAfter",
        ["Transfer.AtOnce"] = "TransferAtOnce",
        ["Transfer.TaskbarProgress"] = "TransferTaskbar",
        ["Transfer.NotifyWhenHidden"] = "TransferNotifyHidden",
        ["Transfer.CancelWhenPhoneLeaves"] = "TransferCancelOnLeave",
        ["Transfer.History"] = "TransferHistory",
        ["Transfer.SendToMenu"] = "TransferSendToMenu",

        ["Apps.OpenOn"] = "AppsOpenOn",
        ["Profiles.PerPhone"] = "ProfilesPerPhone",
        ["Profiles.WhenFullscreen"] = "ProfilesFullscreen",
        ["Profiles.WhenOnBattery"] = "ProfilesBattery",
        ["Profiles.AfterApplying"] = "ProfilesAfter",
        ["Profiles.Keys"] = "ProfilesKeys",
        ["Profiles.InTray"] = "ProfilesInTray",
        ["Profiles.Announce"] = "ProfilesAnnounce",
        ["Profiles.PutBack"] = "ProfilesPutBack",
        ["SecondScreen.Placement"] = "ScreenPlacement",
        ["SecondScreen.Side"] = "ScreenSide",
        ["SecondScreen.Size"] = "ScreenSize",
        ["SecondScreen.CustomWidth"] = "ScreenCustomWidth",
        ["SecondScreen.CustomHeight"] = "ScreenCustomHeight",
        ["SecondScreen.Portrait"] = "ScreenPortrait",
        ["SecondScreen.Dpi"] = "ScreenDpi",
        ["SecondScreen.MaxSize"] = "ScreenMaxSize",
        ["SecondScreen.Decorations"] = "ScreenDecorations",
        ["SecondScreen.KeepAppsOnClose"] = "ScreenKeepApps",
        ["SecondScreen.Keyboard"] = "ScreenKeyboard",
        ["SecondScreen.ReopenOnStart"] = "ScreenReopen",
        ["SecondScreen.ResizeWhileDragging"] = "ScreenResizeWhileDragging",
        ["SecondScreen.MinWidth"] = "ScreenMinWidth",
        ["Views.Arrangement"] = "ViewsArrangement",
        ["Views.Outline"] = "ViewsOutline",
        ["Views.Captions"] = "ViewsCaptions",
        ["Views.Splitter"] = "ViewsSplitter",
        ["SecondPhone.Enabled"] = "SecondPhoneEnabled",
        ["SecondPhone.WhenConnected"] = "SecondPhoneWhen",
        ["SecondPhone.Remember"] = "SecondPhoneRemember",
        ["SecondPhone.Side"] = "SecondPhoneSide",
        ["SecondPhone.Sound"] = "SecondPhoneSound",
        ["SecondPhone.ScreenOff"] = "SecondPhoneScreenOff",
        ["SecondPhone.MaxSize"] = "SecondPhoneMaxSize",
        ["SecondPhone.BitRate"] = "SecondPhoneBitRate",
        ["SecondPhone.PauseWhenHidden"] = "SecondPhonePause",
        ["SecondPhone.FollowsProfile"] = "SecondPhoneProfile",
    };

    /// <summary>
    /// The settings that are passed to scrcpy, so they apply the next time the mirror starts (the
    /// app offers a restart); every other setting applies at once. A test changes each setting and
    /// checks this against the arguments scrcpy would be started with.
    /// </summary>
    public static readonly IReadOnlySet<string> NextStart = new HashSet<string>(StringComparer.Ordinal)
    {
        "Mirror.MaxSize", "Mirror.MaxFps", "Mirror.VideoBitRate", "Mirror.VideoCodec",
        "Mirror.Audio", "Mirror.AudioDup", "Mirror.AudioSource", "Mirror.AudioBitRate",
        "Mirror.VideoBufferMs", "Mirror.DownsizeOnError", "Mirror.RenderDriver", "Mirror.RecordFormat",
        "Mirror.RecordOnStart", "Mirror.ExtraArgs", "Mirror.CompatibilityKeyboard",
        "Session.TurnScreenOff", "Session.StayAwake", "Session.PowerOffOnClose",
        "Mirror.AudioCodec", "Mirror.AudioBufferMs", "Mirror.RecordDirectory",
        "Session.ScreenOffTimeoutSeconds", "Session.KeepPcAwake", "Session.StartApp", "Session.KeepActive",
        "Input.RightClick", "Input.MiddleClick", "Input.BackButton", "Input.ForwardButton",
        "Input.ShiftClicks", "Input.KeyRepeat", "Input.MouseHover", "Input.ClipboardAutosync",
        "Input.LegacyPaste", "Input.Gamepad",
        "Transfer.Enabled",
    };

    /// <summary>Whether a setting applies at once, or the next time the mirror starts.</summary>
    public static bool AppliesAtNextStart(string path) => NextStart.Contains(path);

    public static readonly IReadOnlyDictionary<string, string> Elsewhere = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Version"] = "Managed by the app.",
        ["Hud.X"] = "Set by dragging the fullscreen controls.",
        ["Hud.Y"] = "Set by dragging the fullscreen controls.",
        ["Session.PreferredSerial"] = "Set by the phone picker.",
    };

    public static readonly IReadOnlySet<string> NotYet = new HashSet<string>(StringComparer.Ordinal)
    {
        "Mirror.AudioCodec", "Mirror.AudioBufferMs", "Mirror.RecordDirectory",
        "Session.KeepActive", "Session.WakeBeforeMirror", "Session.DismissKeyguard", "Session.PreferUsb",
        "Session.PollSeconds", "Session.RetrySeconds", "Wireless.Port", "Wireless.ManualHosts",
        "Touchpad.Enabled", "Zoom.WheelZoom", "Zoom.PinchZoom", "PatternGuide.AskPerDevice",
        "PatternGuide.CalibrationEnabled", "PatternGuide.ShowCursorTrail", "PatternGuide.Opacity",
        "Logging.Enabled", "Logging.MaxBytes", "Logging.KeepFiles",
    };
}
