<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>RexMirror</AssemblyName>
    <RootNamespace>Rex.Mirror</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\assets\rex.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>Android Headless Mirror</AssemblyTitle>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rex.Core\Rex.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\assets\rex.ico" Link="Assets\rex.ico" />
    <InternalsVisibleTo Include="Rex.Tests" />
  </ItemGroup>
</Project>
